### ISSUE TITLE
Updating pre-existing catalog and functional profiling

### ISSUE THREAD

**Issue by sarpiens** [EBI-Metagenomics/genomes-pipeline#61]
Hi, I had a couple of questions regarding the pipeline and the generated catalogues:

- I was wondering, if you could guide me through the process of updating a pre-existing catalogue. This is something I've seen you mention in the release, but I haven't seen it documented in the github.

- I was wondering which of the generated catalogue files would be used to make a functional metagenome profile and which program could I use (Humann3, etc)?

Thank you very much in advance.
Best regards, Sam

**Comment by tgurbich** [comment]
Hi Sam,

The update process is described in the methods section of the MGnify Genomes publication [here](https://www.sciencedirect.com/science/article/pii/S0022283623000724). We don't yet have a public pipeline for this but it is coming within a year or so.

As for the functional metagenome profile, I am afraid it is too broad of a question for us to advise you on. It probably wouldn't make sense to do it for a catalogue since it is a collection of many samples. Generally speaking, tools like Humann3 and DRAM can be used for this but the inputs would depend on your goals.

Best wishes,
Tanya

**Comment by tgurbich** [comment]
Hi Sam,

We describe all files available as part of the catalogue in the associated README file on our [FTP](http://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_genomes/). For example, [here](http://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_genomes/human-gut/v2.0.1/README_v2.0.1.txt) is the file for the human gut catalogue. I would suggest checking these to see what files, if any, would be appropriate for the tool you would like to use.

Best wishes,
Tanya
